[package]
name = "posixutils-calc"
version = "0.1.7"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
gettext-rs.workspace = true
regex.workspace = true

[[bin]]
name = "expr"
path = "src/expr.rs"

