[package]
name = "posixutils-calc"
version = "0.1.7"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
gettext-rs.workspace = true
regex.workspace = true
clap.workspace = true
pest = "2.7.10"
pest_derive = "2.7.10"
lazy_static = "1.4.0"
bigdecimal = "0.4.3"
rustyline = { version = "14.0.0", default-features = false }

[[bin]]
name = "expr"
path = "src/expr.rs"

[[bin]]
name = "bc"
path = "src/bc.rs"
