workspace = { members = ["test-manager"] }
[package]
name = "m4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["cargo", "derive"] }
nom = "7.1.3"
libc = "0.2.153"
once_cell = "1.19.0"
circular = "0.3.0"
thiserror = "1.0.59"
log = "0.4.21"
env_logger = "0.11.3"

[dev-dependencies]
insta = { version = "1.38.0", features = ["json"] }
test-log = { version = "0.2.16", default-features=false, features=["log"]}
similar-asserts = "1.5.0"
m4-test-manager = { path = "./test-manager" }

[build-dependencies]
m4-test-manager = { path = "./test-manager" }

