[package]
name = "m4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["cargo"] }
nom = "7.1.3"
libc = "0.2.153"
once_cell = "1.19.0"

[dev-dependencies]
insta = { version = "1.38.0", features = ["json"] }
