[workspace]
resolver = "2"

members = [
	"calc",
	"datetime",
	"dev",
	"display",
	"file",
	"fs",
    "m4",
	"misc",
	"pathnames",
	"plib",
	"process",
	"screen",
	"sys",
	"text",
	"tree",
	"users",
	"xform"
]

