[workspace]
resolver = "2"

members = [
	"calc",
	"datetime",
	"dev",
	"display",
	"file",
	"fs",
	"misc",
	"pathnames",
	"plib",
	"process",
	"screen",
	"sys",
	"text",
	"tree",
	"users",
	"xform"
]

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
libc = "0.2"
regex = "1.10"
