[package]
name = "posixutils-dev"
version = "0.1.7"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
object = "0.33"

[[bin]]
name = "nm"
path = "src/nm.rs"

