[package]
name = "posixutils-process"
version = "0.1.0"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
libc = "0.2"

[[bin]]
name = "env"
path = "src/env.rs"

[[bin]]
name = "nice"
path = "src/nice.rs"

