[package]
name = "posixutils-tree"
version = "0.1.1"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }

[[bin]]
name = "rmdir"
path = "src/rmdir.rs"

