[package]
name = "posixutils-text"
version = "0.1.0"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }

[[bin]]
name = "asa"
path = "src/asa.rs"

[[bin]]
name = "head"
path = "src/head.rs"

[[bin]]
name = "wc"
path = "src/wc.rs"

