[package]
name = "posixutils-xform"
version = "0.1.0"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
crc32fast = "1.4"

[[bin]]
name = "cksum"
path = "src/cksum.rs"

