[package]
name = "posixutils-xform"
version = "0.1.0"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
crc32fast = "1.4"
uuencode = "0.1"
base64 = "0.21"

[[bin]]
name = "cksum"
path = "src/cksum.rs"

[[bin]]
name = "uudecode"
path = "src/uudecode.rs"

[[bin]]
name = "uuencode"
path = "src/uuencode.rs"

